### ISSUE TITLE
Native linking failed, undefined Objective-C class: WebPDecoder.

### ISSUE THREAD

**Issue by dylanvdbrink** [luberda-molinet/WebP.Touch#4]
Hi,

I get the following error when trying to deploy an Xamarin.iOS app to a physical device, where I need to use FFImageLoading which uses WebP.Touch as a dependency. It doesn't give the error when deploying to the simulator.

```
MTOUCH: error MT5211: Native linking failed, undefined Objective-C class: WebPDecoder. The symbol '_OBJC_CLASS_$_WebPDecoder' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH: error MT5202: Native linking failed. Please review the build log.
```

Is this a known issue or am I doing something wrong?

Thanks in advance!

**Comment by dylanvdbrink** [comment]
Could this be the fix?

> To fix the problem, you'll need to add the [Protocol] attribute (as requested by the error message), and then recompile the binding library. If you don't have access to the source for the binding library, the author of the library will have to perform this step.

From [here](https://forums.xamarin.com/discussion/16489/new-type-registrar-in-xamarin-ios-7-2-1-errors-mt5210-and-mt5211#latest)

**Comment by molinch** [comment]
Yes it could be that simple. However I am no longer working with Xamarin so feel free to fork and propose a PR if you solved it!

**Comment by jphenow** [comment]
Fixed in #7!

**Comment by molinch** [comment]
Many thanks @jphenow :+1: 

@daniel-luberda Would it be possible for you to repackage it? If not I can do it, but it will take me hips of time since my Mac environment has not been touched for ages

**Comment by jphenow** [comment]
I couldn't find instruction on any special build requirements or steps but I built it using `nuget pack` ¯\_(ツ)_/¯ [here](https://cl.ly/222o2i1D0t3v) if that's all that's needed.

Note: we were just having issues building FFImageLoading as a result of this attribute missing, we don't actually use WebP.Touch directly so I haven't verified that all of its facilities work as a result of how I built it.

**Comment by daniel-luberda** [comment]
@molinch Sure, I'll build it. Give me a minute :)

**Comment by molinch** [comment]
@jphenow new version uploaded on nuget.org
Thanks @daniel-luberda !

**Comment by jphenow** [comment]
Great, thanks so much!
