### ISSUE TITLE
Change date of DLL in the future cause error with nuget on mono

### ISSUE THREAD

**Issue by WebDucer** [luberda-molinet/WebP.Touch#6]
If I try to restore package on macOS (Nuget CLI) I get the following error.

```
Errors in packages.config projects
    Error downloading 'WebP.Touch.1.0.2' from 'https://api.nuget.org/v3-flatcontainer/webp.touch/1.0.2/webp.touch.1.0.2.nupkg'.
    Invalid parameter
```

After search, I found, that a date in the future cause this error with nuget API v3. Your DLL in the package has the change date of `2089-10-7T15:04`.

**Comment by molinch** [comment]
@WebDucer could you try again with the newest version uploaded? (1.0.3)

**Comment by WebDucer** [comment]
Yes. Now it is working 👍
