### ISSUE TITLE
Image not loaded with iOS 11.2

### ISSUE THREAD

**Issue by Benesss** [luberda-molinet/WebP.Touch#8]
Hi Daniel, Salut Fabien,

It seems that Apple changed something in iOS 11.2 that breaks the display of WebP images.
Please try to run the project on iOS 11.2 (simulator or real device).

Current: the screen remains black. The image is not displayed. No error is thrown.
Expected: the downloaded image should be decoded and displayed.

Thanks for your support guys :)

**Comment by molinch** [comment]
I think it's easy to fix, we just need the same fix:
https://github.com/wantedly/iOS-WebP/commit/89aa62f28b9ff8f7d5e5a1c46dc46b9fef4bfc4e

In the file: https://github.com/luberda-molinet/WebP.Touch/blob/master/xcode/WebPWrapper/WebPDecoder.m#L91

I cannot do it I don't have a Mac, neither XCode. But @Benesss feel free to do a PR ;-)

**Comment by daniel-luberda** [comment]
@molinch  I'll do it & release new nuget :)

**Comment by Benesss** [comment]
Many thanks guys :)

**Comment by molinch** [comment]
Fixed by PR https://github.com/luberda-molinet/WebP.Touch/pull/9
Daniel do you think you could package it? This blocks my colleague

**Comment by daniel-luberda** [comment]
Done :) https://www.nuget.org/packages/WebP.Touch/1.0.5

I also reduced lib size by 2.5MB using `WebPDecoder` instead `WebP` (which contains both encoder & decoder). 🎆 🎆 🎆 

![screen shot 2017-12-07 at 14 56 52](https://user-images.githubusercontent.com/13569983/33718774-e8155a16-db5e-11e7-9313-bd6cad3eac00.png)

**Comment by molinch** [comment]
Wow you truly rock, thanks Daniel!
